"""
src/data/preprocess.py

Builds the training dataset from raw audio files.

What this file does:
--------------------
1. Loads clean speech from LibriSpeech
2. Loads noise from MUSAN + DEMAND (Kaggle) or synthetic (LG Gram)
3. Resamples everything to 8kHz
4. Mixes speech + noise at random SNR (-5 to +20 dB)
5. Applies A-law encode → decode roundtrip to the mixture
6. Cuts into 160-sample (20ms) frames
7. Saves paired (noisy_input, clean_target) arrays

Output structure:
    data/processed/
        X_noisy.npy   shape: [N, 160]  — model input  (A-law distorted + noisy)
        y_clean.npy   shape: [N, 160]  — model target (clean speech)

Usage:
    python src/data/preprocess.py --fraction 0.02   # LG Gram
    python src/data/preprocess.py --fraction 1.0    # Kaggle
"""

import sys
import argparse
import numpy as np
from pathlib import Path
from tqdm import tqdm
import random

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.training.config import (
    DATA_RAW, DATA_PROC, FRACTION,
    SOURCE_SR, TARGET_SR, FRAME_SIZE, HOP_SIZE,
    SNR_MIN, SNR_MAX, SEED
)
from src.utils.audio import (
    load_audio, resample_to_8k, normalize_audio,
    mix_at_snr, make_frames
)
from src.utils.alaw import alaw_roundtrip_numpy


# ─── File Collection ──────────────────────────────────────────────────────────

def collect_speech_files(fraction: float) -> list:
    """
    Collect LibriSpeech .flac files.
    Uses dev-clean for LG Gram, train-clean-100 for Kaggle.
    """
    if fraction < 1.0:
        speech_root = DATA_RAW / "librispeech" / "LibriSpeech" / "dev-clean"
    else:
        speech_root = DATA_RAW / "librispeech" / "LibriSpeech" / "train-clean-100"

    if not speech_root.exists():
        raise FileNotFoundError(
            f"Speech data not found at {speech_root}\n"
            f"Run: python src/data/download.py --fraction {fraction}"
        )

    files = list(speech_root.rglob("*.flac"))
    if not files:
        raise FileNotFoundError(f"No .flac files found in {speech_root}")

    random.seed(SEED)
    random.shuffle(files)

    if fraction < 1.0:
        keep = max(10, int(len(files) * fraction))
        files = files[:keep]

    print(f"  Speech files: {len(files)}")
    return files


def collect_noise_files(fraction: float) -> list:
    """
    Collect noise .wav files.
    Uses synthetic noise for LG Gram, MUSAN+DEMAND for Kaggle.
    """
    noise_files = []

    if fraction < 1.0:
        # Synthetic noise — generated by download.py
        synthetic_dir = DATA_RAW / "synthetic_noise"
        if synthetic_dir.exists():
            noise_files.extend(list(synthetic_dir.rglob("*.wav")))
    else:
        # MUSAN noise + music
        musan_dir = DATA_RAW / "musan" / "musan"
        if musan_dir.exists():
            noise_files.extend(list((musan_dir / "noise").rglob("*.wav")))
            noise_files.extend(list((musan_dir / "music").rglob("*.wav")))

        # DEMAND room noise
        demand_dir = DATA_RAW / "demand"
        if demand_dir.exists():
            noise_files.extend(list(demand_dir.rglob("*.wav")))

    if not noise_files:
        raise FileNotFoundError(
            f"No noise files found.\n"
            f"Run: python src/data/download.py --fraction {fraction}"
        )

    random.seed(SEED + 1)
    random.shuffle(noise_files)

    print(f"  Noise files:  {len(noise_files)}")
    return noise_files


# ─── Audio Loading ────────────────────────────────────────────────────────────

def load_and_resample(filepath: Path, source_sr: int) -> np.ndarray:
    """Load audio file and resample to 8kHz."""
    try:
        audio = load_audio(str(filepath))
        audio = resample_to_8k(audio, source_sr)
        return audio
    except Exception as e:
        return None


def get_noise_segment(noise_files: list, length: int) -> np.ndarray:
    """
    Get a noise segment of exactly `length` samples.
    Randomly selects a noise file and loops it if too short.
    """
    # Try random noise files until we get one that works
    for _ in range(10):
        noise_path = random.choice(noise_files)
        noise = load_audio(str(noise_path))
        if noise is None or len(noise) < 100:
            continue

        # Determine source sample rate from path
        # MUSAN and DEMAND are 16kHz, synthetic is already 8kHz
        if "synthetic" in str(noise_path):
            sr = TARGET_SR
        else:
            sr = SOURCE_SR

        noise = resample_to_8k(noise, sr)

        # Loop noise if shorter than speech
        if len(noise) < length:
            repeats = (length // len(noise)) + 2
            noise = np.tile(noise, repeats)

        # Random crop to exact length
        start = random.randint(0, len(noise) - length)
        return noise[start: start + length].astype(np.float32)

    # Fallback — white noise
    return np.random.randn(length).astype(np.float32) * 0.1


# ─── Frame Pair Builder ───────────────────────────────────────────────────────

def build_frame_pairs(
    speech_files: list,
    noise_files: list,
    fraction: float
) -> tuple:
    """
    Build (noisy_input, clean_target) frame pairs.

    For each speech file:
        1. Load and resample to 8kHz
        2. Normalize speech
        3. Get matching noise segment
        4. Mix at random SNR
        5. Apply A-law roundtrip to mixture → this is the model input
        6. Cut both mixture and clean speech into 160-sample frames
        7. Store paired frames

    Returns:
        X_noisy: np.ndarray [N, 160] — model inputs
        y_clean: np.ndarray [N, 160] — clean targets
    """
    X_list = []
    y_list = []

    min_length = FRAME_SIZE * 4  # at least 4 frames per file

    for speech_path in tqdm(speech_files, desc="  Processing"):
        # Load speech
        speech = load_and_resample(speech_path, SOURCE_SR)
        if speech is None or len(speech) < min_length:
            continue

        # Normalize
        speech = normalize_audio(speech, target_level=0.3)

        # Get noise segment same length as speech
        noise = get_noise_segment(noise_files, len(speech))
        noise = normalize_audio(noise, target_level=0.3)

        # Random SNR for this utterance
        snr = random.uniform(SNR_MIN, SNR_MAX)

        # Mix speech + noise
        mixture = mix_at_snr(speech, noise, snr_db=snr)

        # Apply A-law codec simulation → model input
        noisy_input = alaw_roundtrip_numpy(mixture)

        # Clean speech → model target (no codec distortion)
        clean_target = speech

        # Cut into frames
        noisy_frames = make_frames(noisy_input, FRAME_SIZE, HOP_SIZE)
        clean_frames  = make_frames(clean_target, FRAME_SIZE, HOP_SIZE)

        # Must have same number of frames
        n_frames = min(len(noisy_frames), len(clean_frames))
        if n_frames == 0:
            continue

        X_list.append(noisy_frames[:n_frames])
        y_list.append(clean_frames[:n_frames])

    if not X_list:
        raise RuntimeError("No frames were generated. Check your audio files.")

    X_noisy = np.concatenate(X_list, axis=0).astype(np.float32)
    y_clean = np.concatenate(y_list, axis=0).astype(np.float32)

    return X_noisy, y_clean


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--fraction", type=float, default=FRACTION,
        help="Fraction of data to use. 0.02=LG Gram, 1.0=Kaggle"
    )
    args = parser.parse_args()

    random.seed(SEED)
    np.random.seed(SEED)

    print("=" * 55)
    print("  NS Research — Preprocessing")
    print("=" * 55)
    mode = "Development (LG Gram)" if args.fraction < 1.0 else "Full (Kaggle)"
    print(f"  Fraction: {args.fraction}  |  Mode: {mode}")
    print(f"  Frame:    {FRAME_SIZE} samples = 20ms at {TARGET_SR}Hz")
    print(f"  SNR:      {SNR_MIN} to {SNR_MAX} dB")
    print("=" * 55)

    # Collect files
    print("\nCollecting files...")
    speech_files = collect_speech_files(args.fraction)
    noise_files  = collect_noise_files(args.fraction)

    # Build frame pairs
    print("\nBuilding frame pairs...")
    print("  (noisy A-law input, clean target)")
    X_noisy, y_clean = build_frame_pairs(speech_files, noise_files, args.fraction)

    # Save
    DATA_PROC.mkdir(parents=True, exist_ok=True)
    x_path = DATA_PROC / "X_noisy.npy"
    y_path = DATA_PROC / "y_clean.npy"

    np.save(x_path, X_noisy)
    np.save(y_path, y_clean)

    # Summary
    print("\n" + "=" * 55)
    print("  Preprocessing Complete")
    print("=" * 55)
    print(f"  X_noisy shape: {X_noisy.shape}")
    print(f"  y_clean shape: {y_clean.shape}")
    print(f"  Total frames:  {len(X_noisy):,}")
    print(f"  Total audio:   {len(X_noisy) * FRAME_SIZE / TARGET_SR / 60:.1f} minutes")
    size_mb = (X_noisy.nbytes + y_clean.nbytes) / 1e6
    print(f"  File size:     {size_mb:.1f} MB")
    print(f"  Saved to:      {DATA_PROC}")
    print("=" * 55)
    print("\n  Next: python src/data/split.py")


if __name__ == "__main__":
    main()